"""Weekly summary notes.

After a sync, each week folder gets a note listing what is in it, which
links belong to that week, and which assessments are coming up - so the
week can be reviewed without opening Moodle at all.

Everything here works offline and costs nothing; the optional AI summary
of the content is layered on top elsewhere.
"""
from __future__ import annotations

import dataclasses
import re
import time
from datetime import datetime, timedelta
from pathlib import Path

from .config import Config

NOTE_PREFIX = "Week"
NOTE_SUFFIX = "Summary"

_DOC_EXT = {".pdf": "PDF", ".docx": "Word", ".doc": "Word",
            ".pptx": "Slides", ".ppt": "Slides", ".xlsx": "Spreadsheet",
            ".xls": "Spreadsheet", ".md": "Note", ".txt": "Text",
            ".mp4": "Video", ".mp3": "Audio", ".zip": "Archive",
            ".c": "Code", ".py": "Code", ".java": "Code", ".ipynb": "Notebook"}

_DUE_FORMATS = ("%A, %d %B %Y, %I:%M %p", "%d %B %Y, %I:%M %p",
                "%A, %d %B %Y", "%d %B %Y")


@dataclasses.dataclass
class Assessment:
    name: str
    due: str
    url: str
    mod: str

    @property
    def due_date(self) -> datetime | None:
        text = (self.due or "").strip()
        for fmt in _DUE_FORMATS:
            try:
                return datetime.strptime(text, fmt)
            except ValueError:
                continue
        return None


@dataclasses.dataclass
class WeekNote:
    unit: str
    week: int
    folder: Path
    links: list[tuple[str, str]] = dataclasses.field(default_factory=list)
    assessments: list[Assessment] = dataclasses.field(default_factory=list)
    # Recordings that exist but carry no captions - worth naming, because
    # otherwise they vanish from the week without trace.
    no_captions: list[tuple[str, str]] = dataclasses.field(default_factory=list)


def _describe(path: Path) -> str:
    kind = _DOC_EXT.get(path.suffix.lower(), path.suffix.lstrip(".").upper() or "File")
    kb = max(1, round(path.stat().st_size / 1024))
    size = f"{kb} KB" if kb < 1024 else f"{kb / 1024:.1f} MB"
    return f"{kind}, {size}"


def _files_in(folder: Path) -> list[Path]:
    if not folder.exists():
        return []
    out = [p for p in sorted(folder.rglob("*"))
           if p.is_file() and not p.name.startswith(".")
           and NOTE_SUFFIX not in p.name and p.parent.name != "images"]
    return out


def _upcoming(assessments: list[Assessment], limit: int = 5) -> list[Assessment]:
    """Assessments still ahead of us, soonest first."""
    cutoff = datetime.now() - timedelta(days=1)
    ahead = [a for a in assessments if a.due_date and a.due_date >= cutoff]
    ahead.sort(key=lambda a: a.due_date or datetime.max)
    return ahead[:limit]


def build_markdown(note: WeekNote) -> str:
    files = _files_in(note.folder)
    lines = [f"# {note.unit} — Week {note.week:02d}", ""]
    stamp = time.strftime("%d %b %Y %H:%M")
    lines += [f"*Generated by Moodle Downloader on {stamp}. "
              f"This file is rewritten on every sync — keep your own notes "
              f"elsewhere.*", "", "---", ""]

    lines += ["## Files this week", ""]
    if files:
        for f in files:
            rel = f.relative_to(note.folder).as_posix()
            lines.append(f"- [{rel}]({rel.replace(' ', '%20')}) — {_describe(f)}")
    else:
        lines.append("*Nothing published yet.*")
    lines.append("")

    if note.links:
        lines += ["## Recordings and links", ""]
        for label, url in note.links:
            lines.append(f"- [{label or url}]({url})")
        lines.append("")

    if note.no_captions:
        lines += ["## Recordings you have to watch yourself", "",
                  "*No captions were published for these, so there is no "
                  "transcript to read.*", ""]
        for label, url in note.no_captions:
            lines.append(f"- [{label or url}]({url})")
        lines.append("")

    soon = _upcoming(note.assessments)
    if soon:
        lines += ["## Assessments coming up", ""]
        for a in soon:
            when = a.due_date.strftime("%a %d %b, %I:%M %p") if a.due_date else a.due
            lines.append(f"- **{a.name}** — due {when}  \n  [Open in Moodle]({a.url})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_note(cfg: Config, note: WeekNote) -> Path | None:
    """Write Week NN Summary.md (and .docx when python-docx is available)."""
    files = _files_in(note.folder)
    if not files and not note.links:
        return None  # nothing happened this week - no point in a note

    note.folder.mkdir(parents=True, exist_ok=True)
    md = build_markdown(note)
    path = note.folder / f"{NOTE_PREFIX} {note.week:02d} {NOTE_SUFFIX}.md"
    previous = path.read_text(encoding="utf-8") if path.exists() else ""
    # Ignore the timestamp line when deciding whether anything really changed.
    strip = lambda s: re.sub(r"\*Generated by.*?\*", "", s, flags=re.S)  # noqa: E731
    if strip(previous) == strip(md):
        return None
    path.write_text(md, encoding="utf-8")
    _write_docx(note, path.with_suffix(".docx"), files)
    return path


def _write_docx(note: WeekNote, path: Path, files: list[Path]) -> None:
    try:
        from docx import Document
        from docx.shared import Pt
    except ImportError:
        return
    try:
        doc = Document()
        doc.add_heading(f"{note.unit} — Week {note.week:02d}", level=1)
        p = doc.add_paragraph(
            f"Generated by Moodle Downloader on {time.strftime('%d %b %Y %H:%M')}. "
            "This file is rewritten on every sync.")
        p.runs[0].font.size = Pt(9)

        doc.add_heading("Files this week", level=2)
        if files:
            for f in files:
                doc.add_paragraph(
                    f"{f.relative_to(note.folder).as_posix()} — {_describe(f)}",
                    style="List Bullet")
        else:
            doc.add_paragraph("Nothing published yet.")

        if note.links:
            doc.add_heading("Recordings and links", level=2)
            for label, url in note.links:
                doc.add_paragraph(f"{label or 'Link'} — {url}", style="List Bullet")

        if note.no_captions:
            doc.add_heading("Recordings you have to watch yourself", level=2)
            for label, url in note.no_captions:
                doc.add_paragraph(f"{label or 'Recording'} — {url}",
                                  style="List Bullet")

        soon = _upcoming(note.assessments)
        if soon:
            doc.add_heading("Assessments coming up", level=2)
            for a in soon:
                when = a.due_date.strftime("%a %d %b, %I:%M %p") if a.due_date else a.due
                doc.add_paragraph(f"{a.name} — due {when}", style="List Bullet")
        doc.save(str(path))
    except Exception:
        pass  # a missing Word copy must never fail a sync
