from __future__ import annotations

from pathlib import Path

from .config import Config, load_config
from .courses import _CODE_RE, Course, fetch_courses
from .session import MoodleSession

DEFAULT_URL = "https://learning.monash.edu"

CONFIG_TEMPLATE = """\
# === Moodle Downloader config (generated by setup) ===

base_url: {base_url}

# Where unit folders are created
root_dir: "{root_dir}"

week_start: 0
week_end: 12

# "manual" = sync the units listed below.
# "starred" = sync whatever you have starred on Moodle (re-star to change).
course_selection: {course_selection}

units:
{units_yaml}
# Regexes matching a section title to a week ({{week}} = week number)
section_patterns:
  - "week\\\\s*0*{{week}}\\\\b"
  - "topic\\\\s*0*{{week}}\\\\b"

# Files from sections that match no week go here ("" = skip them)
unmatched_folder: "_Other"

skip_extensions: []
"""


def _temp_config(base_url: str, config_path: Path) -> Config:
    return Config(
        base_url=base_url, root_dir=config_path.parent / "MoodleFiles",
        week_start=0, week_end=12, units=[], section_patterns=[],
        unmatched_folder="_Other", skip_extensions=[],
        config_dir=config_path.parent, course_selection="manual",
    )


def _ask(prompt: str, default: str) -> str:
    val = input(f"{prompt} [{default}]: ").replace("﻿", "").strip()
    return val or default


def run_setup(config_path: Path) -> Config | None:
    print()
    print("=== Moodle Downloader - first-time setup ===")
    print()
    base_url = _ask("Moodle address (press Enter if you are at Monash)",
                    DEFAULT_URL).rstrip("/")
    default_root = str(config_path.parent / "MoodleFiles")
    root_dir = _ask("Folder where course files should be saved", default_root)

    print()
    print("Now fetching your course list from Moodle.")
    print("If a browser window opens, log in with your university account")
    print("(tick 'Keep me signed in' so this rarely happens again).")
    print()

    with MoodleSession(_temp_config(base_url, config_path)) as sess:
        courses = fetch_courses(sess, base_url, "all")

    courses.sort(key=lambda c: -c.startdate)
    print(f"Found {len(courses)} enrolled courses (* = starred on Moodle):")
    print()
    for i, c in enumerate(courses, 1):
        star = "*" if c.starred else " "
        print(f"  {i:2d}. {star} {c.fullname[:75]}")
    print()
    print("Which courses should be synced?")
    print("  - numbers separated by commas, e.g.:  1,2,3,4")
    print("  - or type  star  to always sync the courses you star on Moodle")
    choice = input("> ").strip().lower()

    if choice in ("star", "starred", "s"):
        course_selection = "starred"
        units_yaml = "  []  # resolved from your starred courses at each run\n"
    else:
        course_selection = "manual"
        picked: list[Course] = []
        try:
            for tok in choice.replace(" ", "").split(","):
                if tok:
                    picked.append(courses[int(tok) - 1])
        except (ValueError, IndexError):
            print("Sorry, I couldn't read that - please run setup again.")
            return None
        if not picked:
            print("Nothing selected - please run setup again.")
            return None
        units_yaml = "".join(
            f"  - code: {c.unit_code}\n    course_id: {c.id}\n" for c in picked)
        print()
        print("Selected: " + ", ".join(c.unit_code for c in picked))

    config_path.write_text(CONFIG_TEMPLATE.format(
        base_url=base_url,
        root_dir=root_dir.replace("\\", "/"),
        course_selection=course_selection,
        units_yaml=units_yaml,
    ), encoding="utf-8")
    print()
    print(f"Setup complete! Settings saved to {config_path}")
    return load_config(config_path)
