from __future__ import annotations

from pathlib import Path

from .config import Config, load_config
from .courses import _CODE_RE, Course, fetch_courses
from .session import MoodleSession

DEFAULT_URL = "https://learning.monash.edu"

CONFIG_TEMPLATE = """\
# === Moodle Downloader config (generated by setup) ===

base_url: {base_url}

# Where unit folders are created
root_dir: "{root_dir}"

week_start: 0
week_end: 12

# "manual" = sync the units listed below.
# "starred" = sync whatever you have starred on Moodle (re-star to change).
course_selection: {course_selection}

units:
{units_yaml}
# Regexes matching a section title to a week ({{week}} = week number)
section_patterns:
  - "week\\\\s*0*{{week}}\\\\b"
  - "topic\\\\s*0*{{week}}\\\\b"

# Files from sections that match no week go here ("" = skip them)
unmatched_folder: "_Other"

# Optional AI summaries of lecture transcripts. Leave ai_provider empty to
# keep everything offline. Providers: gemini (free tier), anthropic, openai,
# deepseek, moonshot, zhipu, qwen, ollama (local, no key).
ai_provider: "{ai_provider}"
ai_api_key: "{ai_api_key}"
ai_model: ""
ai_base_url: ""

# Assignment briefs + an assessments index go here ("" = disable)
assignments_folder: "Assignments"

# Auto-sync repeat interval in hours (used when auto-sync is turned on)
sync_interval_hours: {sync_interval_hours}

# Weekly summary note per week folder (Markdown + Word)
weekly_notes: {weekly_notes}

# Save captions of lecture recordings as transcripts
transcripts: {transcripts}

skip_extensions: []
"""


def _temp_config(base_url: str, config_path: Path) -> Config:
    return Config(
        base_url=base_url, root_dir=config_path.parent / "MoodleFiles",
        week_start=0, week_end=12, units=[], section_patterns=[],
        unmatched_folder="_Other", skip_extensions=[],
        config_dir=config_path.parent, course_selection="manual",
    )


def write_config(config_path: Path, base_url: str, root_dir: str,
                 course_selection: str, picked: list[Course],
                 ai_provider: str = "", ai_api_key: str = "",
                 sync_interval_hours: float = 3,
                 weekly_notes: bool = True,
                 transcripts: bool = True) -> Config:
    """Write config.yaml - shared by the CLI wizard and the GUI."""
    if course_selection == "starred":
        units_yaml = "  []  # resolved from your starred courses at each run\n"
    else:
        units_yaml = "".join(
            f"  - code: {c.unit_code}\n    course_id: {c.id}\n" for c in picked)
    config_path.write_text(CONFIG_TEMPLATE.format(
        base_url=base_url.rstrip("/"),
        root_dir=root_dir.replace("\\", "/"),
        course_selection=course_selection,
        units_yaml=units_yaml,
        ai_provider=ai_provider.strip(),
        ai_api_key=ai_api_key.strip().replace('"', ""),
        sync_interval_hours=f"{sync_interval_hours:g}",
        weekly_notes=str(bool(weekly_notes)).lower(),
        transcripts=str(bool(transcripts)).lower(),
    ), encoding="utf-8")
    return load_config(config_path)


def _ask(prompt: str, default: str) -> str:
    val = input(f"{prompt} [{default}]: ").replace("﻿", "").strip()
    return val or default


def run_setup(config_path: Path) -> Config | None:
    print()
    print("=== Moodle Downloader - first-time setup ===")
    print()
    base_url = _ask("Moodle address (press Enter if you are at Monash)",
                    DEFAULT_URL).rstrip("/")
    root_dir = _ask("Folder where course files should be saved",
                    "MoodleFiles, next to this app")
    if root_dir == "MoodleFiles, next to this app":
        root_dir = str(config_path.parent / "MoodleFiles")

    print()
    print("Now fetching your course list from Moodle.")
    print("If a browser window opens, log in with your university account")
    print("(tick 'Keep me signed in' so this rarely happens again).")
    print()

    with MoodleSession(_temp_config(base_url, config_path)) as sess:
        courses = fetch_courses(sess, base_url, "all")

    courses.sort(key=lambda c: -c.startdate)
    print(f"Found {len(courses)} enrolled courses (* = starred on Moodle):")
    print()
    for i, c in enumerate(courses, 1):
        star = "*" if c.starred else " "
        print(f"  {i:2d}. {star} {c.fullname[:75]}")
    print()
    print("Which courses should be synced?")
    print("  - numbers separated by commas, e.g.:  1,2,3,4")
    print("  - or type  star  to always sync the courses you star on Moodle")
    # tolerate full-width (Chinese IME) commas and stray spaces
    choice = (input("> ").replace("，", ",").replace("、", ",")
              .strip().lower())

    picked: list[Course] = []
    if choice in ("star", "starred", "s"):
        course_selection = "starred"
    else:
        course_selection = "manual"
        try:
            for tok in choice.replace(" ", "").split(","):
                if tok:
                    picked.append(courses[int(tok) - 1])
        except (ValueError, IndexError):
            print("Sorry, I couldn't read that - please run setup again.")
            return None
        if not picked:
            print("Nothing selected - please run setup again.")
            return None
        print()
        print("Selected: " + ", ".join(c.unit_code for c in picked))

    # Re-running setup must not silently reset settings made elsewhere.
    keep = {}
    if config_path.exists():
        try:
            old = load_config(config_path)
            keep = dict(ai_provider=old.ai_provider, ai_api_key=old.ai_api_key,
                        sync_interval_hours=old.sync_interval_hours,
                        weekly_notes=old.weekly_notes,
                        transcripts=old.transcripts)
        except Exception:
            pass
    cfg = write_config(config_path, base_url, root_dir,
                       course_selection, picked, **keep)
    print()
    print("Setup complete! Settings saved to config.yaml next to the app.")
    return cfg
